config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions'
  }, skip: %w[registrations]

  root to: 'application#redirect_to_sign_in'

  resources :admin_users, only: %w[#<WebFront:0x00007ffa4cf05750>]

  namespace :api do
    namespace :v1 do
      resources :books, except: %i[new edit]

      post 'sign_in', controller: 'users/sessions', action: 'create'
    end
  end

  namespace :dashboard do
    # TODO: customizable table name
    devise_for :admin_users, controllers: {
      sessions: 'dashboard/admin_users/sessions',
      passwords: 'dashboard/admin_users/passwords'
    }, skip: %w[registrations]

    resources :admin_users
  end

  get '*path' => redirect('/')

  unless Rails.env.development?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      admin_username = ENV['SIDEKIQ_DASHBOARD_USERNAME']
      admin_password = ENV['SIDEKIQ_DASHBOARD_PASSWORD']
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(username),
        ::Digest::SHA256.hexdigest(admin_username)
      ) && ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(password),
        ::Digest::SHA256.hexdigest(admin_password)
      )
    end
  end
  mount Sidekiq::Web => '/sidekiq'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable,
         :trackable, :recoverable

  has_many :books, dependent: :destroy

  validates :age, numericality: { only_integer: true, greater_than: 0, allow_blank: true }

  scope :by_name, ->(name) { where(arel_table[:name].matches("%#{name}%")) }
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  before_action :set_admin_user, only: %w[edit update destroy]

  def index
    @admin_users = AdminUser.order(created_at: :desc).page(params[:page])
  end

  private

  def set_admin_user
    @admin_user = AdminUser.find_by(id: params[:id])
  end

  def admin_user_params
    params.require(:admin_user).permit(
      :created_at, :updated_at, :email, :name, :password, :email
    )
  end
end

app/controllers/dashboard/admin_users/passwords_controller.rb
module Dashboard
  module AdminUsers
    class PasswordsController < Devise::PasswordsController
      layout 'dashboard_not_authenticated'

      def update
        self.resource = resource_class.reset_password_by_token(resource_params)
        yield resource if block_given?
        if resource.errors.empty?
          resource.unlock_access! if unlockable?(resource)
          if Devise.sign_in_after_reset_password
            flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
            set_flash_message!(:notice, flash_message)
            resource.after_database_authentication
            sign_in(resource_name, resource)
          else
            flash[:notice] = t('.success')
          end
          respond_with resource, location: after_resetting_user_password_path_for(resource)
        else
          set_minimum_password_length
          @error = resource.errors.full_messages.join(', ')
          respond_with resource
        end
      end

      private

      def after_resetting_admin_user_password_path_for(_)
        new_dashboard_admin_user_session_path
      end
    end
  end
end

app/controllers/dashboard/admin_users/sessions_controller.rb
module Dashboard
  module AdminUsers
    class SessionsController < Devise::SessionsController
      layout 'dashboard_not_authenticated'

      def after_sign_in_path_for(_)
        dashboard_admin_users_path
      end

      def after_sign_out_path_for(_)
        new_dashboard_admin_user_session_path
      end
    end
  end
end

app/controllers/dashboard/admin_users_controller.rb
module Dashboard
  class AdminUsersController < BaseController
    before_action :set_admin_user, only: %w[show edit update]
    helper_method :order_params

    def index
      service = Search::AdminUsersService.new(search_params)
      @admin_users = service.execute
    end

    def new
      @admin_user = AdminUser.new
    end

    def create
      @admin_user = AdminUser.new
      save_admin_user('created', :new)
    end

    def show; end

    def edit; end

    def update
      save_admin_user('updated', :edit)
    end

    def destroy
      flash[:notice] = if admin_user_destroyed?
                         'Admin user destroyed successfully.'
                       else
                         'Admin user could not be destroyed.'
                       end
      redirect_to dashboard_admin_users_path
    end

    def order_params(order, direction)
      params.merge(o: order, d: direction, page: params[:page], q: params[:q]).permit(:o, :d, :page, q: :name)
    end

    private

    def save_admin_user(action, form_partial)
      inputs = { admin_user: @admin_user, attrs: admin_user_params }
      outcome = ::AdminUsers::CreateOrUpdate.run(inputs)

      if outcome.valid?
        flash[:notice] = "Admin user #{action} successfully."
        redirect_to dashboard_admin_user_path(outcome.result)
      else
        flash[:notice] = "Admin user could not be #{action}."
        @admin_user = outcome.result
        render form_partial
      end
    end

    def search_params
      params[:o] = params[:o].presence || params.dig(:q, :o)
      params[:d] = params[:d].presence || params.dig(:q, :d)
      order_params(params[:o], params[:d])
    end

    def set_admin_user
      @admin_user = AdminUser.find_by(id: params[:id])
    end

    def admin_user_destroyed?
      ::AdminUsers::Destroy.run({ id: params[:id] }).valid?
    end

    def admin_user_params
      params.require(:admin_user).permit(
        :email, :name, :password, :password_confirmation, :age, :phone, :address
      )
    end
  end
end

app/controllers/dashboard/base_controller.rb
module Dashboard
  class BaseController < ApplicationController
    layout 'dashboard'
    before_action :authenticate_dashboard_admin_user!
  end
end

app/views/dashboard/admin_users/_admin_user_header.html.slim
.main-content
  .container-fluid
    .header
      .header-body
        .row.d-flex.justify-content-between
          .col
            .header-pretitle
              h6 = t('.heading_sub')
            h1.header-title = AdminUser.model_name.human
          .mx-4.pt-2
            = render 'breadcrumb', data: [{ text: AdminUser.model_name.human.pluralize, link: '/dashboard/admin_users' }, { text: breadcrumb_action_text, link: breadcrumb_action_link }]

    .row.justify-content-center
      .col-12.col-lg-10.col-xl-8
        .card
          = yield

app/views/dashboard/admin_users/_breadcrumb.html.slim
.d-flex
  - data.each do |item|
    .ml-2.d-flex
      = link_to item[:text], item[:link]
      - if item != data.last
        .ml-2 >

app/views/dashboard/admin_users/_form_fields.html.slim
- %i[email name age address phone].each do |attr|
  .form-group
    = f.input attr, input_html: { autocomplete: attr }
.form-group
  = f.input :password, input_html: { autocomplete: 'current-password' }
.form-group
  = f.input :password_confirmation, input_html: { autocomplete: 'current-password' }

.form-actions
  = f.button :submit, t('.save'), class: 'btn btn-primary btn-sm'

app/views/dashboard/admin_users/edit.html.slim
- model_name_human = AdminUser.model_name.human

= render 'admin_user_header', breadcrumb_action_text: "#{t('.edit')} #{model_name_human}", breadcrumb_action_link: "/dashboard/admin_users/#{@admin_user.id}/edit" do
  .card-header
    h4.card-header-title = "#{t('.edit')} #{model_name_human}"
  .card-body
    = simple_form_for(@admin_user, url: dashboard_admin_user_path(@admin_user), method: :put) do |f|
      = render 'form_fields', f: f

app/views/dashboard/admin_users/index.html.slim
.main-content
  .container-fluid
    .header
      .header-body
        .row.align-items-end
          .col
            .header-pretitle
              h6 = t('.heading_sub')
            h1.header-title = AdminUser.model_name.human
          .col-auto
            = link_to t('.csv'), dashboard_admin_users_path(admin_user: @search_query, format: :csv), class: 'btn btn-info lift ml-3'

    = simple_form_for :q, url: dashboard_admin_users_path, method: :get do |f|
      = f.input :name, label: 'Enter name of the admin user', input_html: { value: params.dig(:q, :name) }
      = f.hidden_field :o, value: params[:o]
      = f.hidden_field :d, value: params[:d]
      = f.button :submit, t('.search'), class: 'btn btn-primary btn-sm', 'data-disable-with' => "#{t('.searching')}..."

    .row.mt-4
      .col-12
        = link_to t('.new_admin_user'), new_dashboard_admin_user_path, class: 'btn btn-primary btn-sm pull-right'

    .row.mt-4
      .col-12
        .card
          .table-responsive
            table.table.table-sm.card-table
              thead
                tr
                  - %w[id email created_at updated_at name age].each do |column|
                    th
                      .d-flex
                        .mr-2 = AdminUser.human_attribute_name(column.to_sym)
                        - if params[:d]&.include?('asc') && params[:o]&.include?(column)
                          = link_to '⋀', dashboard_admin_users_path(order_params(column, 'desc'))
                        - else
                          = link_to '⋁', dashboard_admin_users_path(order_params(column, 'asc'))
                  th
              tbody
                - @admin_users.each do |admin_user|
                  tr
                    td = admin_user.id
                    td = admin_user.email
                    td = formatted_date(admin_user.created_at)
                    td = formatted_date(admin_user.updated_at)
                    td = admin_user.name
                    td = admin_user.age
                    td = link_to t('.show'), dashboard_admin_user_path(admin_user), class: 'btn btn-primary btn-sm'
                    td = link_to t('.edit'), edit_dashboard_admin_user_path(admin_user), class: 'btn btn-primary btn-sm'
                    td = link_to t('.delete'), dashboard_admin_user_path(admin_user), class: 'btn btn-primary btn-sm', method: :delete

        = paginate @admin_users, views_prefix: 'dashboard'

app/views/dashboard/admin_users/new.html.slim
- model_name_human = AdminUser.model_name.human

= render 'admin_user_header', breadcrumb_action_text: "#{t('.new')} #{model_name_human}", breadcrumb_action_link: "/dashboard/admin_users/new" do
  .card-header
    h4.card-header-title = "#{t('.new')} #{model_name_human}"
  .card-body
    = simple_form_for(@admin_user, url: dashboard_admin_users_path, method: :post) do |f|
      = render 'form_fields', f: f

app/views/dashboard/admin_users/show.html.slim
= render 'admin_user_header', breadcrumb_action_text: "#{t('.view')} #{AdminUser.model_name.human}", breadcrumb_action_link: "/dashboard/admin_users/#{@admin_user.id}" do
  .card-header
    h4.card-header-title = "#{AdminUser.model_name.human} #{t('.detailed_information')}"
  .card-body
    .list-group.list-group-flush.my-n3
      - %i[created_at updated_at].each do |attr|
          .list-group-item
            .row.align-items-center
              .col
                .font-weight-base.mb-1 = AdminUser.human_attribute_name(attr)
              .col-auto
                = formatted_date(@admin_user.send(attr))
      - %i[email name age address phone].each do |attr|
          .list-group-item
            .row.align-items-center
              .col
                .font-weight-base.mb-1 = AdminUser.human_attribute_name(attr)
              .col-auto
                = @admin_user.send(attr)